@hostname = localhost
@port1 = 8080
@port = 8081
# @host = templateapp.app/api/v1.0
@host = {{hostname}}:{{port}}

@contentType = application/json


###
# @name Register
POST http://{{hostname}}:{{port1}}/users
Content-Type: {{contentType}}

{
    "full_name":"Rishabh",
    "username": "rk3",
    "email": "rk3@flow.com",
    "password": "Qwe@123456"
}


###
# @name login
POST http://{{hostname}}:{{port1}}/users/login
Content-Type: {{contentType}}

{
    "username": "rk3",
    "password": "Qwe@123456"
}

@login_token = {{login.response.body.access_token}}


###
GET http://{{host}}/deployment/1
Content-Type: {{contentType}}
Authorization: Bearer {{login_token}}

###
POST http://{{host}}/deployment/add
Content-Type: {{contentType}}
Authorization: Bearer {{login_token}}

{
  "name": "user-service",
  "environment": "dev",
  "components": [
    {
      "name": "user",
      "image": {
        "repository": "rishabh75/templateapp-user",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 9069,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "500Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "500Mi"
        }
      },
      "env": [
        {
          "key": "MODE",
          "value": "server"
        },
        {
          "key": "SERVER_TYPE",
          "value": "USER"
        }
      ]
    }
  ]
}

# ###
# GET http://{{host}}/cores?page_id=1&page_size=5
# Content-Type: {{contentType}}
# Authorization: Bearer {{login_token}}
