@hostname = localhost
@port1 = 9069
@port = 8081
# @host = orbitdeck.app/api/core
# @authHost = orbitdeck.app/api/auth
@authHost = {{hostname}}:{{port1}}
@host = {{hostname}}:{{port}}

@contentType = application/json

###
# @name Register
POST http://{{authHost}}/users
Content-Type: {{contentType}}

{
    "full_name":"Rishabh",
    "username": "rk1",
    "email": "rk1@flow.com",
    "password": "Qwe@123456"
}


###
# @name login
POST http://{{authHost}}/users/login
Content-Type: {{contentType}}

{
    "username": "rk1",
    "password": "Qwe@123456"
}

###
GET http://{{host}}/deployment?pageNo=1
Content-Type: {{contentType}}

###
GET http://{{host}}/deployment/48
Content-Type: {{contentType}}

###
DELETE  http://{{host}}/deployment/48
Content-Type: {{contentType}}

###
GET http://{{host}}/deployment/48/status


###
POST http://{{host}}/deployment/add
Content-Type: {{contentType}}

{
  "name": "user-service",
  "environment": "dev",
  "components": [
    {
      "name": "user",
      "image": {
        "repository": "rishabh75/sample-node",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 9069,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "500Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "500Mi"
        }
      },
      "env": [
        {
          "key": "MODE",
          "value": "server"
        },
        {
          "key": "SERVER_TYPE",
          "value": "USER"
        }
      ]
    }
  ],
  "ingress": {
        "host": "orbitdeck.app"
  }
}


###
POST http://{{host}}/deployment/add
Content-Type: {{contentType}}

{
  "name": "main",
  "environment": "dev",
  "components": [
     {
      "name": "internal-postgres",
      "image": {
        "repository": "postgres:14.10-alpine3.19",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 5432,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "500Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "500Mi"
        }
      },
      "env": [
        {
          "key": "POSTGRES_USER",
          "value": "root"
        },
        {
          "key": "POSTGRES_PASSWORD",
          "value": "root"
        },
        {
          "key": "POSTGRES_DB",
          "value": "be-orbitdeck"
        }
      ]
    },
    {
      "name": "user",
      "image": {
        "repository": "rishabh75/orbitdeck-user",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 9069,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "500Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "500Mi"
        }
      },
      "env": [
        {
          "key": "MODE",
          "value": "server"
        },
        {
          "key": "SERVER_TYPE",
          "value": "USER"
        }
      ]
    },
    {
      "name": "client",
      "image": {
        "repository": "rishabh75/orbitdeck-client",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 3000,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "1000Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "1000Mi"
        }
      },
      "env": [
        {
          "key": "API_URL",
          "value": "https://orbitdeck.app/api/user"
        },
        {
          "key": "ENV",
          "value": "development"
        },
        {
          "key": "PORT",
          "value": "3000"
        }
      ]
    }
  ],
  "ingress": {
        "host": "orbitdeck.app"
  }
}


###
POST http://{{host}}/deployment/add
Content-Type: {{contentType}}

{
  "name": "main",
  "environment": "dev",
  "components": [
     {
      "name": "internal-postgres",
      "image": {
        "repository": "postgres:14.10-alpine3.19",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 5432,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "500Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "500Mi"
        }
      },
      "env": [
        {
          "key": "POSTGRES_USER",
          "value": "root"
        },
        {
          "key": "POSTGRES_PASSWORD",
          "value": "root"
        },
        {
          "key": "POSTGRES_DB",
          "value": "be-orbitdeck"
        }
      ]
    },
    {
      "name": "user",
      "image": {
        "repository": "rishabh75/orbitdeck-user",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 9069,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "500Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "500Mi"
        }
      },
      "env": [
        {
          "key": "MODE",
          "value": "server"
        },
        {
          "key": "SERVER_TYPE",
          "value": "USER"
        }
      ]
    },
    {
      "name": "client",
      "image": {
        "repository": "rishabh75/orbitdeck-client",
        "tag": "latest"
      },
      "replica_count": 1,
      "service_port": 3000,
      "resources": {
        "requests": {
          "cpu": "1",
          "memory": "1000Mi"
        },
        "limits": {
          "cpu": "1",
          "memory": "1000Mi"
        }
      },
      "env": [
        {
          "key": "API_URL",
          "value": "https://orbitdeck.app/api/user"
        },
        {
          "key": "ENV",
          "value": "development"
        },
        {
          "key": "PORT",
          "value": "3000"
        }
      ]
    }
  ],
  "ingress": [
        {
            "host": "orbitdeck.app",
            "path": "/api/user/?(.*)",
            "serviceName": "user-svc",
            "servicePort": 9069
        },
  ]
}

