# cronjob-template

{{- range .Values.cronJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .name }}-cron
        spec:
          containers:
            - name: {{ .name }}-cron
              image: "{{ .image }}"
              resources:
                requests:
                  cpu: "{{ .resources.requests.cpu }}"
                  memory: "{{ .resources.requests.memory }}"
                limits:
                  cpu: "{{ .resources.limits.cpu }}"
                  memory: "{{ .resources.limits.memory }}"
              envFrom:
                - configMapRef:
                    name: common-config
                - secretRef:
                    name: common-secrets
              env:
                - name: MODE
                  value: "cron"
          restartPolicy: OnFailure
---
{{- end }}
