export const routesObj = {
    auth: "/auth",
    home: "/",
    groupId: "/group/:groupId",
    groupAdd: "/groups/add",
    members: "/members",
    membersAdd: "/members/add",
    me: "/me",
};

export const tech = [
    "js",
    "ts",
    "react",
    "nextjs",
    "nodejs",
    "express",
    "prisma",
    "postgres",
    "redis",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "git",
    "github",
    "githubactions",
    "tailwind",
    "vite",
    "graphql",
    "mysql",
    "mongodb",
    "flutter",
    "py",
    "django",
    "fastapi",
    "vercel",
    "supabase",
    "jest",
];
