// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddMemberToGroup(ctx context.Context, arg AddMemberToGroupParams) error
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateGroup(ctx context.Context, name string) (Group, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	DeleteExpense(ctx context.Context, id int32) error
	DeleteGroup(ctx context.Context, id int32) error
	DeleteMember(ctx context.Context, id int32) error
	GetExpensesByGroup(ctx context.Context, groupID int32) ([]Expense, error)
	GetGroupByID(ctx context.Context, id int32) (Group, error)
	GetMemberByID(ctx context.Context, id int32) (Member, error)
	GetMembersByGroup(ctx context.Context, groupID int32) ([]GetMembersByGroupRow, error)
	RemoveMemberFromGroup(ctx context.Context, arg RemoveMemberFromGroupParams) error
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	UpdateMember(ctx context.Context, arg UpdateMemberParams) error
}

var _ Querier = (*Queries)(nil)
