// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (EnvVar, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateIngress(ctx context.Context, arg CreateIngressParams) (Ingress, error)
	CreateResources(ctx context.Context, arg CreateResourcesParams) (Resource, error)
	DeleteIngress(ctx context.Context, id int64) error
	GetComponentEnvVars(ctx context.Context, componentID int64) ([]GetComponentEnvVarsRow, error)
	GetDeployment(ctx context.Context, id int64) (Deployment, error)
	GetDeploymentComponents(ctx context.Context, deploymentID int64) ([]GetDeploymentComponentsRow, error)
	GetIngressByDeployment(ctx context.Context, deploymentID int64) ([]Ingress, error)
	GetIngressByHost(ctx context.Context, host string) (Ingress, error)
}

var _ Querier = (*Queries)(nil)
