// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AddCoreBalance(ctx context.Context, arg AddCoreBalanceParams) (Core, error)
	CreateCore(ctx context.Context, arg CreateCoreParams) (Core, error)
	DeleteCore(ctx context.Context, id int64) error
	GetCore(ctx context.Context, id int64) (Core, error)
	GetCoreForUpdate(ctx context.Context, id int64) (Core, error)
	ListCores(ctx context.Context, arg ListCoresParams) ([]Core, error)
	UpdateCore(ctx context.Context, arg UpdateCoreParams) (Core, error)
}

var _ Querier = (*Queries)(nil)
