apiVersion: skaffold/v4beta8
kind: Config

.COMMON_ARTIFACTS:
  ARTIFACTS_DEFINITION:
    - &AUTH
      image: rishabh75/orbitdeck-auth
      context: ../../server/auth
      sync:
        manual:
          - src: src/**/*.go
            dest: .
      docker:
        dockerfile: ../Dockerfiles/Dockerfile.main
    - &CORE
      image: rishabh75/orbitdeck-core
      context: ../../server/core
      sync:
        manual:
          - src: src/**/*.go
            dest: .
      docker:
        dockerfile: ../Dockerfiles/Dockerfile.main
    - &EMAIL
      image: rishabh75/orbitdeck-email
      context: ../../server/auth
      sync:
        manual:
          - src: src/**/*.go
            dest: .
      docker:
        dockerfile: ../Dockerfiles/Dockerfile.email
    # - &CLIENT
    #   image: rishabh75/orbitdeck-client
    #   context: ../../client/
    #   sync:
    #     manual:
    #       - src: src/**/*.js
    #         dest: .
    #   docker:
    #     dockerfile: ../Dockerfiles/Dockerfile.client
    # - &CLIENT-PROD
    #   image: rishabh75/orbitdeck-client-prod
    #   context: ../../client/
    #   sync:
    #     manual:
    #       - src: src/**/*.js
    #         dest: .
    #   docker:
    #     dockerfile: ../Dockerfiles/Dockerfile.client-prod
    # - &MIGRATE
    #   image: rishabh75/orbitdeck-internal-migration
    #   context: ../../server/auth
    #   docker:
    #     dockerfile: ../Dockerfiles/Dockerfile.migrate
  COMMON_ARTIFACTSETS:
    DEFAULT_ARTIFACTS: &DEFAULT_ARTIFACTS # - *MIGRATE
      - *AUTH
      - *CORE
      - *EMAIL
      # - *CLIENT
    DEV_ARTIFACTS: &DEV_ARTIFACTS # - *MIGRATE
      - *AUTH
      - *CORE
      - *EMAIL
      # - *CLIENT
    PROD_ARTIFACTS: &PROD_ARTIFACTS # - *MIGRATE
      - *AUTH
      - *CORE
      - *EMAIL
      # - *EMAIL
      # - *CRON
      # - *CLIENT-PROD

# build: &DEFAULT_BUILD
#   local:
#     push: false
#   artifacts: *DEFAULT_ARTIFACTS
# deploy:
#   helm:
#     releases:
#       - name: orbitdeck-release
#         chartPath: ../helm/
#         createNamespace: true
#         valuesFiles:
#           - ../helm/values/dev.yaml

profiles:
  - name: dev
    deploy:
      helm:
        releases:
          - name: orbitdeck-dev-release
            chartPath: ../helm/
            namespace: orbitdeck-dev
            createNamespace: true
            wait: true
            valuesFiles:
              - ../helm/values/dev.yaml
    build:
      local:
        push: true
      tagPolicy:
        sha256: {}
      artifacts: *DEV_ARTIFACTS

  - name: prod
    deploy:
      helm:
        releases:
          - name: orbitdeck-prod-release
            chartPath: ../helm/
            namespace: orbitdeck-prod
            createNamespace: true
            wait: true
            valuesFiles:
              - ../helm/values/prod.yaml
    build:
      local:
        push: true
      tagPolicy:
        sha256: {}
        # dateTime: {}
      artifacts: *PROD_ARTIFACTS

  - name: server
    deploy:
      helm:
        releases:
          - name: orbitdeck-server-release
            chartPath: ../helm/
            namespace: orbitdeck-server
            createNamespace: true
            wait: true
            valuesFiles:
              - ../helm/values/server.yaml

    # build:
    #   local:
    #     push: true
    #   tagPolicy:
    #     gitCommit: {}
    #   artifacts: *PROD_ARTIFACTS
