apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-config
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rishabhkanojiya75@gmail.com
    privateKeySecretRef:
      name: issuer-config
    solvers:
      - http01:
          ingress:
            class: nginx
