@hostname = localhost
@port1 = 6969
@port = 6970
# @host = templateapp.app/api/v1.0
@host = {{hostname}}:{{port}}

@contentType = application/json


###
# @name login
POST http://{{hostname}}:{{port1}}/users/login
Content-Type: {{contentType}}

{
    "username": "rk5",
    "password": "Qwe@123456"
}

@login_token = {{login.response.body.access_token}}


###
GET http://{{host}}/accounts/1
Content-Type: {{contentType}}
Authorization: Bearer {{login_token}}

###
POST http://{{host}}/accounts
Content-Type: {{contentType}}
Authorization: Bearer {{login_token}}

{
    "currency": "CAD"
}

###
GET http://{{host}}/accounts?page_id=1&page_size=5
Content-Type: {{contentType}}
Authorization: Bearer {{login_token}}
