@baseUrl = https://orbitdeck.app/api/analytics
# @baseUrl = http://localhost:8090

###
GET {{baseUrl}}/events/recent?userEmail=rk1

###
GET {{baseUrl}}/events/stats?userEmail=rk1

###
GET {{baseUrl}}/events/component/usage?userEmail=rk1

###
GET {{baseUrl}}/events/timeline?userEmail=rk1

###
GET {{baseUrl}}/events/errors?userEmail=rk1
