COMPONENT_DEFINITION:
  - &INTERNAL-POSTGRES
    name: internal-postgres
    replicaCount: 1
    # hooks:
    #   helm.sh/resource-policy: keep
    #   helm.sh/hook-delete-policy: before-hook-creation
    image:
      repository: postgres:14.10-alpine3.19
      tag: latest
    resources:
      requests:
        cpu: "1"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
    service:
      name: "db"
      port: 5432
    env:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "be-orbitdeck"
    volume:
      path: /var/lib/postgresql/data
      subPath: postgres
      claimName: postgres-pvc
  - &EMAIL-REDIS
    name: email-redis
    replicaCount: 1
    image:
      repository: redis
      tag: latest
    resources:
      requests:
        cpu: "1"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
    service:
      name: "caching"
      port: 6379
  - &AUTH
    name: auth
    replicaCount: 1
    image:
      repository: rishabh75/orbitdeck-auth
      tag: latest
    resources:
      requests:
        cpu: "1"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
    service:
      port: 9069
    env:
      SERVER_PORT: 9069
  # - &CORE
  #   name: core
  #   replicaCount: 1
  #   image:
  #     repository: rishabh75/orbitdeck-core
  #     tag: latest
  #   resources:
  #     requests:
  #       cpu: "1"
  #       memory: "500Mi"
  #     limits:
  #       cpu: "1"
  #       memory: "500Mi"
  #   service:
  #     port: 9069
  - &EMAIL
    name: email
    replicaCount: 1
    image:
      repository: rishabh75/orbitdeck-email
      tag: latest
    resources:
      requests:
        cpu: "1"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "500Mi"
    env:
      MODE: "worker"
      SERVER_TYPE: "email-worker"
      EMAIL_SENDER_NAME: Nikki Parker
      EMAIL_SENDER_ADDRESS: nikki96@ethereal.email
      EMAIL_SENDER_PASSWORD: vyPM1PtxuRee7MGZZe

INGRESS_DEFINITION: &INGRESS_DEFINITION
  - &DEV_INGRESS
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    rules:
      - host: orbitdeck.app
        paths:
          - path: /api/auth/?(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: auth-svc
              servicePort: 9069
          - path: /api/core/?(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: core-svc
              servicePort: 9069
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: client-svc
              servicePort: 3000

# jobs:
#   - name: internal-migration
#     completions: 1
#     backoffLimit: 1
#     enabled: true
#     image:
#       repository: rishabh75/orbitdeck-internal-migration
#       tag: latest
#       pullPolicy: IfNotPresent
#     resources:
#       requests:
#         cpu: "1"
#         memory: "500Mi"
#       limits:
#         cpu: "1"
#         memory: "500Mi"
#     env:
#       MODE: "server"
#       SERVER_TYPE: "internal"

volumes:
  - name: postgres
    storage: 1Gi

# cronJobs:
#   - name: email-cron-job
#     schedule: "*/30 * * * *"
#     successfulJobsHistoryLimit: 3
#     failedJobsHistoryLimit: 1
#     concurrencyPolicy: "Forbid"
#     image: rishabh75/orbitdeck-email-cron
#     resources:
#       requests:
#         cpu: "1"
#         memory: "500Mi"
#       limits:
#         cpu: "1"
#         memory: "500Mi"

DEV_COMPONENTS: &DEV_COMPONENTS
  - *INTERNAL-POSTGRES
  - *EMAIL-REDIS
  - *AUTH
  # - *CORE
  - *EMAIL
  # - *CLIENT

components: *DEV_COMPONENTS

ingress: *DEV_INGRESS
